CUDA_VISIBLE_DEVICES=0 python3 main.py train \
                                --crop-size 256 256 \
                                --save-interval 2 \
                                --batch-size 16 \
                                --epochs 100 \
                                --lr 5e-5 \
                                --data-dir ../Datasets \
                                --ssim_weight 0.2 \
                                --perc_weight 0.001 \
                                --gan_weight 0.005 \
                                --save-dir ./logs
